[package]
name = "file-ninja"
version = "0.0.2"
edition = "2021"

[lib]
name = "fini"
path = "src/lib.rs"

[[bin]]
name = "file-ninja"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
strum = "0.26"
strum_macros = "0.26"
clap_mangen = "0.2.23"
