name: Tests
run-name: ${{ github.actor }} is building RustyFileNinja

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      ninja_version: ''
      release_id: ''
      release_filename: ''
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test FileNinja
        run: |
          cargo test
